name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Run lints, checks and tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update local toolchain
      run: |
        rustup update
        rustup component add clippy
        rustup component add rustfmt
    - name: Toolchain info
      run: |
        cargo --version --verbose
        rustc --version
        cargo clippy --version
    - name: Lint
      run: |
        cargo fmt -- --check
        cargo clippy -- -D warnings
    - name: Test
      run: |
        cargo check
        cargo test
    - name: Build
      run: |
        cargo build --verbose
