name: publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  qa:
    uses: ./.github/workflows/main.yml
  publish:
    name: Publish a new release to crates.io
    needs: qa
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Publish Crate
      run: cargo publish --token ${CRATES_IO_TOKEN}
      env:
        CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
